Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,14 +30,28 @@ jobs:
           export VAULT_ADDR="http://47.128.235.138:8200/"
           export VAULT_TOKEN="${{ secrets.VAULT_TOKEN }}"
           AWS_CREDS=$(vault kv get -format=json aws-static/creds)
+          
+          # Check if AWS_CREDS is not empty and extract the credentials
+          if [ -z "$AWS_CREDS" ]; then
+            echo "Error: AWS credentials not retrieved from Vault"
+            exit 1
+          fi
+          
           export AWS_ACCESS_KEY_ID=$(echo $AWS_CREDS | jq -r '.data.access_key')
           export AWS_SECRET_ACCESS_KEY=$(echo $AWS_CREDS | jq -r '.data.secret_key')
-          # Mask keys from logs
+          
+          # Mask AWS credentials in the logs for security
           echo "::add-mask::$AWS_ACCESS_KEY_ID"
           echo "::add-mask::$AWS_SECRET_ACCESS_KEY"
-          
+
       - name: Configure AWS CLI
         run: |
+          # Ensure the AWS keys are not empty
+          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+            echo "Error: AWS credentials are missing"
+            exit 1
+          fi
+
           aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
           aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
           aws configure set region ap-southeast-1
